#!/bin/bash
# Filename:      grml-lang
# Purpose:       load specific keyboard layout settings
# Authors:       grml-team (grml.org), (c) Michael Prokop <mika@grml.org>, (c) Christian Haase
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
################################################################################

CONFFILE=/etc/default/keyboard
PN="$(basename $0)"

usage(){
    echo "Usage: $0 <language>"
    echo "supported values: at, ch, de, dvorak, es, fr, it, jp, us"
}

setvalue(){
  # already present in conffile?
  if grep -q ${1} $CONFFILE 2>/dev/null ; then
     sudo sed -i "s#^${1}.*#${1}=${2}#"   $CONFFILE
  else
     echo "$1=${2}" | sudo tee -a $CONFFILE >/dev/null
  fi
}

if [ $# -lt "1" ] ; then
   usage
   exit 1
fi


LANGUAGE="$1"

KBMODEL=
KBLAYOUT=
KBVARIANT=
KBOPTIONS=
KBBACKSPACE=

. /etc/grml/language-functions

# any kind of warning if no config matched

setvalue XKBMODEL "$KBMODEL"
setvalue XKBLAYOUT "$KBLAYOUT"
setvalue XKBVARIANT "$KBVARIANT"
setvalue XKBOPTIONS "$KBOPTIONS"
setvalue BACKSPACE "${KBBACKSPACE:=guess}"

if [ -z "$DISPLAY" ]; then
  setupcon --keyboard-only 
  case $LANG in *UTF-8) kbd_mode -u ; ;; esac
else
  udevadm trigger --subsystem-match=input --action=change
fi

## END OF FILE #################################################################
