#!/bin/bash
# Filename:      grml-chroot
# Purpose:       Program to chroot into another system
# Authors:       grml-team (grml.org), (c) Michael Gebetsroither <gebi@grml.org>
# Bug-Reports:   see http://grml.org/bugs/
# License:       This file is licensed under the GPL v2.
################################################################################

PROG_NAME_=$(basename $0)
DEST_=""
MOUNTED_=""     # all mounted destinations

function bailout
{
  umount_all
  die "Bailout"
}
trap bailout 1 2 3 3 6 9 14 15

function die
{
    echo "Error: $@" >&2
    exit 1
}

function isMounted
{
    local dir="$1"
    if cut -d\  -f 2 /proc/mounts | grep -q "$dir"; then
        return 0
    else
        return 1
    fi
}

function printUsage
{
    cat <<EOT
Usage: "$PROG_NAME_" NEWROOT [COMMAND....]

$PROG_NAME_ is a chroot wrapper with proc/sys/pts/dev filesystem handling

EOT
}

function storeMounts
{
    local to_append_="$1"
    if [[ $MOUNTED_ == "" ]]; then
        MOUNTED_="$to_append_"
    else
        MOUNTED_="$MOUNTED_ $to_append_"
    fi
}

function mountit
{
    local type_="$1" # type _or_ src
    local dest_="$2"
    local options_="$3"

    local all_options_=""

    if ! isMounted "${DEST_}/$dest_"; then
      if [[ $options_ == "--bind" ]]; then
        all_options_="--bind $type_"
      else
        all_options_="-t $type_ none"
      fi
      mount $all_options_ "${DEST_}/$dest_" && storeMounts "$dest_"
    fi
}

function umount_all
{
    for i in /proc /sys /dev; do
        umount "${DEST_}/${i}"
    done

    rm -f "$DEST_"/etc/debian_chroot
}


###
### __MAIN
###

while getopts "h" opt; do
    case "$opt" in
        h) printUsage; exit 0 ;;
        ?) printUsage; exit 64 ;;
    esac
done
shift $(($OPTIND - 1))

if (( $# < 1 )); then
    printUsage
    die "Wrong number of arguments."
fi

DEST_="$1"; shift

if [ ! -d "$DEST_" ]; then
    die "Target chroot does not exist: $DEST_"
fi


mountit "proc"  "proc"
mountit "sysfs" "sys"
mountit "/dev"   "dev"   "--bind"

# do not write to /var/run of chroot if it's not present
if [ -d "$DEST_/tmp" ] ; then
  STATEDIR="tmp/grml-chroot"
  mkdir -p "$DEST_/$STATEDIR"
  touch "$DEST_/$STATEDIR/$$"
fi

if [ ! -e "$DEST_"/etc/debian_chroot ]; then
    echo "Writing /etc/debian_chroot ..."
    cat "$DEST_"/etc/hostname > "$DEST_"/etc/debian_chroot
fi

if (( $# < 1 )); then
    chroot "$DEST_"
    RC=$?
else
    chroot "$DEST_" "$@"
    RC=$?
fi

if [ -z "$STATEDIR" ] ; then
  umount_all
else
  rm "$DEST_/$STATEDIR/$$"

  if rmdir "$DEST_/$STATEDIR" 2>/dev/null; then
    umount_all
  fi
fi

exit $RC
